name: newsapi
services:
  postgres:
    image: postgres:16
    container_name: newsapi-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  news-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsapi-app
    ports:
      - "8666:8666"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
