{
 "title": "News API Endpoint Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate (req/sec) per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(news_api_app_requests_total{url!=\"/metrics\"}[1m])",
     "legendFormat": "{{ method }} {{ url }}"
    }
   ]
  },
  {
   "title": "Average Request Duration (s) per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(news_api_app_request_duration_seconds_sum{url!=\"/metrics\"}[1m]) / rate(news_api_app_request_duration_seconds_count[1m])",
     "legendFormat": "{{ method }} {{ url }}"
    }
   ]
  },
  {
   "title": "95th Percentile Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(news_api_app_request_duration_seconds_bucket[1m])) by (le, path))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Error Rate (5xx only)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(news_api_app_requests_total{code=~\"5..\"}[1m])",
     "legendFormat": "{{ method }} {{ path }}"
    }
   ]
  },
  {
   "title": "Average Response Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(news_api_app_response_size_bytes_sum[1m]) / rate(news_api_app_response_size_bytes_count[1m])",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}